#!/bin/bash

http_proxy=
https_proxy=
no_proxy=

win_user=
node_path=

export http_proxy=$http_proxy
export https_proxy=$https_proxy
export no_proxy=$no_proxy
echo "toor" | sudo -S /bin/sh -c `echo "Acquire::http::Proxy \"$http_proxy";" > /etc/apt/apt.conf.d/99proxy`

echo """export http_proxy=$http_proxy
export https_proxy=$https_proxy
export no_proxy=$no_porxy""" > ~/proxy/set


{
    jsonStr=$(cat "/mnt/c/Users/$win_user/AppData/Roaming/Code/User/settings.json")
    if [ -z "$jsonStr" ]; then
        return
    fi
    res=$($node_path -p "{
            try{
                var json_str = JSON.parse(JSON.stringify($jsonStr))
                if(!json_str['http.proxy']){
                    json_str['http.proxy'] = '$http_proxy'
                }
                JSON.stringify(json_str)
            }catch{
                JSON.stringify($jsonStr)
            }
        }
    ")
    # Check if res is not empty and not "undefined" or "null"
    if [ -z "$res" ] || [ "$res" == "undefined" ] || [ "$res" == "null" ]; then
        return
    fi
    echo $res > "/mnt/c/Users/$win_user/AppData/Roaming/Code/User/settings.json"
    } || {
    return
}